name: PR

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Use Node.js LTS versions
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: corepack enable
      - run: yarn install

      # - name: yarn lint
      #   run: yarn lint

      - name: yarn build
        run: yarn build

      - name: yarn test (excluding e2e)
        run: yarn test --exclude "**/e2e/**"
